# Generated by Django 5.0.2 on 2024-03-09 17:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('recovery_answer', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='JWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expiration_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanpost.users')),
            ],
            options={
                'db_table': 'jwt',
            },
        ),
        migrations.CreateModel(
            name='aws_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=14)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('aws_access_key_id', models.CharField(max_length=100)),
                ('aws_secret_access_key', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanpost.users')),
            ],
            options={
                'db_table': 'aws_credentials',
            },
        ),
    ]
