# Generated by Django 5.0.2 on 2024-03-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djanpost', '0002_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expiration_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djanpost.users')),
            ],
            options={
                'db_table': 'jwt',
            },
        ),
    ]
