# Generated by Django 5.0.2 on 2024-03-19 15:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aws_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=14)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('aws_access_key_id', models.CharField(max_length=100)),
                ('aws_secret_access_key', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'aws_credentials',
            },
        ),
    ]
